# Generated by Django 3.0.2 on 2020-02-12 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='description',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='sallary',
            field=models.CharField(default='Negociabil', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_expire',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 13, 19, 36, 17, 168459, tzinfo=utc)),
        ),
    ]
