# Generated by Django 3.0.2 on 2020-02-13 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('job_list', '0002_auto_20200212_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_expire',
            field=models.DateField(default=datetime.datetime(2020, 3, 14, 17, 19, 37, 364385, tzinfo=utc)),
        ),
    ]
